-- ----------------------------
-- Table structure for ui_template
-- ----------------------------
CREATE TABLE  IF NOT EXISTS `ui_template` (
  `ui_template_id` bigint(20) NOT NULL COMMENT 'UI模板ID',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `ui_template_name` varchar(200) NOT NULL COMMENT 'UI页面模板名称',
  `ui_template_type` varchar(200) NOT NULL COMMENT '模板类型，html/html5/android',
  `ui_template_model` varchar(200) NOT NULL default 'Waterfall' COMMENT '模板模式，套模板，瀑布式：Waterfall,多页签：MultiTab等',
  `ui_template_desc` varchar(2000) DEFAULT NULL COMMENT 'UI模板描述',
  `public_flag` char(1) NOT NULL DEFAULT 'N' COMMENT '跨租户共享标识，Y是，N否',
  `text_column1` varchar(2000) COMMENT '预留文本字段1',
  `text_column2` varchar(2000) COMMENT '预留文本字段2',
  `text_column3` varchar(2000) COMMENT '预留文本字段3',
  `text_column4` varchar(2000) COMMENT '预留文本字段4',
  `text_column5` varchar(2000) COMMENT '预留文本字段5',
  `int_column1` bigint(20) COMMENT '预留整数字段1',
  `int_column2` bigint(20) COMMENT '预留整数字段2',
  `int_column3` bigint(20) COMMENT '预留整数字段3',
  `num_column1` decimal(30,8) COMMENT '预留数值字段1',
  `num_column2` decimal(30,8) COMMENT '预留数值字段2',
  `num_column3` decimal(30,8) COMMENT '预留数值字段3',
  `date_column1` datetime COMMENT '预留日期字段1',
  `date_column2` datetime COMMENT '预留日期字段2',
  `date_column3` datetime COMMENT '预留日期字段3',
  `active_flag` char(1) NOT NULL DEFAULT 'Y' COMMENT '有效标识，Y有效，N无效',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` bigint(20) NOT NULL COMMENT '创建人ID，对用用户ID',
  `last_update_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '最后更新时间',
  `last_update_by` bigint(20) NOT NULL COMMENT '最后更新人ID，对用用户ID',
  PRIMARY KEY (`ui_template_id`),
  UNIQUE KEY `ui_template_id` (`ui_template_id`),
  KEY `ui_template_tenant_id_fk0` (`tenant_id`),
  CONSTRAINT `ui_template_tenant_id_fk0` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI页面模板';

-- ----------------------------
-- Table structure for ui_entity_rel
-- ----------------------------
CREATE TABLE  IF NOT EXISTS `ui_entity_rel` (
  `ui_entity_rel_id` bigint(20) NOT NULL COMMENT 'UI模板和实体关系ID',
  `ui_template_id` bigint(20) COMMENT 'UI模板ID，为空，则为但对象，参考entity_id',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `entity_type` varchar(200) NOT NULL COMMENT '实体类型，Entity、View',
  `entity_id` bigint(20) NOT NULL COMMENT '元数据实体ID',
  `entity_sequence` int(10) NOT NULL COMMENT '实体顺序号',
  `ui_entity_rel_desc` varchar(2000) DEFAULT NULL COMMENT 'UI模板与实体关系描述',
  `public_flag` char(1) NOT NULL DEFAULT 'N' COMMENT '跨租户共享标识，Y是，N否',
  `text_column1` varchar(2000) COMMENT '预留文本字段1',
  `text_column2` varchar(2000) COMMENT '预留文本字段2',
  `text_column3` varchar(2000) COMMENT '预留文本字段3',
  `text_column4` varchar(2000) COMMENT '预留文本字段4',
  `text_column5` varchar(2000) COMMENT '预留文本字段5',
  `int_column1` bigint(20) COMMENT '预留整数字段1',
  `int_column2` bigint(20) COMMENT '预留整数字段2',
  `int_column3` bigint(20) COMMENT '预留整数字段3',
  `num_column1` decimal(30,8) COMMENT '预留数值字段1',
  `num_column2` decimal(30,8) COMMENT '预留数值字段2',
  `num_column3` decimal(30,8) COMMENT '预留数值字段3',
  `date_column1` datetime COMMENT '预留日期字段1',
  `date_column2` datetime COMMENT '预留日期字段2',
  `date_column3` datetime COMMENT '预留日期字段3',
  `active_flag` char(1) NOT NULL DEFAULT 'Y' COMMENT '有效标识，Y有效，N无效',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` bigint(20) NOT NULL COMMENT '创建人ID，对用用户ID',
  `last_update_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '最后更新时间',
  `last_update_by` bigint(20) NOT NULL COMMENT '最后更新人ID，对用用户ID',
  PRIMARY KEY (`ui_entity_rel_id`),
  UNIQUE KEY `ui_entity_rel_id` (`ui_entity_rel_id`),
  KEY `ui_entity_rel_tenant_id_fk0` (`tenant_id`),
  CONSTRAINT `ui_entity_rel_tenant_id_fk0` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`),
  KEY `ui_entity_rel_template_id_fk0` (`ui_template_id`),
  CONSTRAINT `ui_entity_rel_template_id_fk0` FOREIGN KEY (`ui_template_id`) REFERENCES `ui_template` (`ui_template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI模板和实体关系';


-- ----------------------------
-- Table structure for ui_fields
-- ----------------------------
CREATE TABLE  IF NOT EXISTS `ui_fields` (
  `ui_fields_id` bigint(20) NOT NULL COMMENT 'UI属性主键ID',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `ui_entity_rel_id` bigint(20) NOT NULL COMMENT 'UI模板和实体关系ID',
  `md_field_id` bigint(20) NOT NULL COMMENT '实体属性ID',
  `ui_fields_type` varchar(200) NOT NULL default 'Basic' COMMENT 'UI属性类型，Basic(继承实体字段的类型)/Int/Lookup等，绑定不同类型页面组件',
  `ui_fields_name_cn` varchar(200) COMMENT 'UI属性中文名称',
  `ui_fields_name_en` varchar(200) COMMENT 'UI属性英文名称',
  `ui_fields_desc` varchar(2000) DEFAULT NULL COMMENT 'UI模板属性描述',
  `field_sequence` int(10)  COMMENT '属性顺序号',
  `linked_field_id` bigint(20) COMMENT '属性联动UI字段',  
  `public_flag` char(1) NOT NULL DEFAULT 'N' COMMENT '跨租户共享标识，Y是，N否',
  `text_column1` varchar(2000) COMMENT '预留文本字段1',
  `text_column2` varchar(2000) COMMENT '预留文本字段2',
  `text_column3` varchar(2000) COMMENT '预留文本字段3',
  `text_column4` varchar(2000) COMMENT '预留文本字段4',
  `text_column5` varchar(2000) COMMENT '预留文本字段5',
  `int_column1` bigint(20) COMMENT '预留整数字段1',
  `int_column2` bigint(20) COMMENT '预留整数字段2',
  `int_column3` bigint(20) COMMENT '预留整数字段3',
  `num_column1` decimal(30,8) COMMENT '预留数值字段1',
  `num_column2` decimal(30,8) COMMENT '预留数值字段2',
  `num_column3` decimal(30,8) COMMENT '预留数值字段3',
  `date_column1` datetime COMMENT '预留日期字段1',
  `date_column2` datetime COMMENT '预留日期字段2',
  `date_column3` datetime COMMENT '预留日期字段3',
  `active_flag` char(1) NOT NULL DEFAULT 'Y' COMMENT '有效标识，Y有效，N无效',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` bigint(20) NOT NULL COMMENT '创建人ID，对用用户ID',
  `last_update_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '最后更新时间',
  `last_update_by` bigint(20) NOT NULL COMMENT '最后更新人ID，对用用户ID',
  PRIMARY KEY (`ui_fields_id`),
  UNIQUE KEY `ui_fields_id` (`ui_fields_id`),
  KEY `ui_fields_tenant_id_fk0` (`tenant_id`),
  CONSTRAINT `ui_fields_tenant_id_fk0` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`),
  KEY `ui_fields_entity_id_fk0` (`ui_entity_rel_id`),
  CONSTRAINT `ui_fields_entity_id_fk0` FOREIGN KEY (`ui_entity_rel_id`) REFERENCES `ui_entity_rel` (`ui_entity_rel_id`),
  KEY `ui_linked_fields_entity_id_fk0` (`linked_field_id`),
  CONSTRAINT `ui_linked_fields_entity_id_fk0` FOREIGN KEY (`linked_field_id`) REFERENCES `ui_fields` (`ui_fields_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='UI属性';
