-- ----------------------------
-- Table structure for docs
-- ----------------------------
CREATE TABLE  IF NOT EXISTS `docs` (
  `doc_id` bigint(20) NOT NULL COMMENT '文档ID',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `doc_l1_category` varchar(200) COMMENT '文档LV1分类',
  `doc_l2_category` varchar(200) COMMENT '文档LV2分类',
  `doc_type` varchar(200) NOT NULL DEFAULT 'File' COMMENT '文档分类，File/Folder',
  `doc_suffix` varchar(200)  COMMENT '文档后缀分类，doc/xls/pdf/xml/ppt',
  `doc_name` varchar(300) NOT NULL COMMENT '文档名称',
  `doc_labels` varchar(1000) COMMENT '文档标签',
  `doc_uuid` varchar(500) COMMENT '文档存储ID',
  `doc_version` decimal(10,3)  COMMENT '文档版本',
  `doc_size` decimal(20,5) NOT NULL COMMENT '文档大小',
  `doc_path` varchar(2000) COMMENT '文档存储路径',
  `doc_status` varchar(200) DEFAULT 'Draft' COMMENT '文档状态，如：Draft草稿，Published已发布',
  `doc_source` varchar(200)  COMMENT '文档来源',
  `watermark_flag` char(1) NOT NULL DEFAULT 'N' COMMENT '水印标识，Y有效，N无效',
  `watermark_date` datetime COMMENT '水印日期',
  `comments` varchar(2000) COMMENT '文档描述',
  `text_column1` varchar(2000) COMMENT '预留文本字段1',
  `text_column2` varchar(2000) COMMENT '预留文本字段2',
  `text_column3` varchar(2000) COMMENT '预留文本字段3',
  `text_column4` varchar(2000) COMMENT '预留文本字段4',
  `text_column5` varchar(2000) COMMENT '预留文本字段5',
  `int_column1` bigint(20) COMMENT '预留整数字段1',
  `int_column2` bigint(20) COMMENT '预留整数字段2',
  `int_column3` bigint(20) COMMENT '预留整数字段3',
  `num_column1` decimal(30,8) COMMENT '预留数值字段1',
  `num_column2` decimal(30,8) COMMENT '预留数值字段2',
  `num_column3` decimal(30,8) COMMENT '预留数值字段3',
  `date_column1` datetime COMMENT '预留日期字段1',
  `date_column2` datetime COMMENT '预留日期字段2',
  `date_column3` datetime COMMENT '预留日期字段3',
  `active_flag` char(1) NOT NULL DEFAULT 'Y' COMMENT '有效标识，Y有效，N无效',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` bigint(20) NOT NULL COMMENT '创建人ID，对用用户ID',
  `last_update_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT '最后更新时间',
  `last_update_by` bigint(20) NOT NULL COMMENT '最后更新人ID，对用用户ID',
  PRIMARY KEY (`doc_id`),
  UNIQUE KEY `doc_id` (`doc_id`),
  KEY `docs_tenant_id_fk0` (`tenant_id`),
  CONSTRAINT `docs_tenant_id_fk0` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='文档信息';
