-- ----------------------------
-- Table structure for system_entities
-- ----------------------------
CREATE TABLE  IF NOT EXISTS `system_entities` (
  `data_id` bigint(20) NOT NULL COMMENT '主键ID',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `md_entity_id` bigint(20) NOT NULL COMMENT '元数据实体ID',  
  `text_column0` varchar(512) COMMENT '预留文本字段0',
  `text_column1` varchar(512) COMMENT '预留文本字段1',
  `text_column2` varchar(512) COMMENT '预留文本字段2',
  `text_column3` varchar(512) COMMENT '预留文本字段3',
  `text_column4` varchar(512) COMMENT '预留文本字段4',
  `text_column5` varchar(512) COMMENT '预留文本字段5',
  `text_column6` varchar(512) COMMENT '预留文本字段6',
  `text_column7` varchar(512) COMMENT '预留文本字段7',
  `text_column8` varchar(512) COMMENT '预留文本字段8',
  `text_column9` varchar(512) COMMENT '预留文本字段9',
  `text_column10` varchar(512) COMMENT '预留文本字段10',
  `text_column11` varchar(512) COMMENT '预留文本字段11',
  `text_column12` varchar(512) COMMENT '预留文本字段12',
  `text_column13` varchar(512) COMMENT '预留文本字段13',
  `text_column14` varchar(512) COMMENT '预留文本字段14',
  `text_column15` varchar(512) COMMENT '预留文本字段15',
  `text_column16` varchar(512) COMMENT '预留文本字段16',
  `text_column17` varchar(512) COMMENT '预留文本字段17',
  `text_column18` varchar(512) COMMENT '预留文本字段18',
  `text_column19` varchar(512) COMMENT '预留文本字段19',
  `text_column20` varchar(512) COMMENT '预留文本字段20',
  `text_column21` varchar(512) COMMENT '预留文本字段21',
  `text_column22` varchar(512) COMMENT '预留文本字段22',
  `text_column23` varchar(512) COMMENT '预留文本字段23',
  `text_column24` varchar(512) COMMENT '预留文本字段24',
  `text_column25` varchar(512) COMMENT '预留文本字段25',
  `text_column26` varchar(512) COMMENT '预留文本字段26',
  `text_column27` varchar(512) COMMENT '预留文本字段27',
  `text_column28` varchar(512) COMMENT '预留文本字段28',
  `text_column29` varchar(512) COMMENT '预留文本字段29',
  `text_column30` varchar(512) COMMENT '预留文本字段30',
  `text_column31` varchar(512) COMMENT '预留文本字段31',
  `text_column32` varchar(512) COMMENT '预留文本字段32',
  `text_column33` varchar(512) COMMENT '预留文本字段33',
  `text_column34` varchar(512) COMMENT '预留文本字段34',
  `text_column35` varchar(512) COMMENT '预留文本字段35',
  `text_column36` varchar(512) COMMENT '预留文本字段36',
  `text_column37` varchar(512) COMMENT '预留文本字段37',
  `text_column38` varchar(512) COMMENT '预留文本字段38',
  `text_column39` varchar(512) COMMENT '预留文本字段39',  
  `char_column0` varchar(10) COMMENT '预留char字段0',
  `char_column1` varchar(10) COMMENT '预留char字段1',
  `char_column2` varchar(10) COMMENT '预留char字段2',
  `char_column3` varchar(10) COMMENT '预留char字段3',
  `char_column4` varchar(10) COMMENT '预留char字段4',
  `char_column5` varchar(10) COMMENT '预留char字段5',
  `char_column6` varchar(10) COMMENT '预留char字段6',
  `char_column7` varchar(10) COMMENT '预留char字段7',
  `char_column8` varchar(10) COMMENT '预留char字段8',
  `char_column9` varchar(10) COMMENT '预留char字段9',
  `int_column1` bigint(20) COMMENT '预留整数字段1',
  `int_column2` bigint(20) COMMENT '预留整数字段2',
  `int_column3` bigint(20) COMMENT '预留整数字段3',
  `int_column4` bigint(20) COMMENT '预留整数字段4',
  `int_column5` bigint(20) COMMENT '预留整数字段5',
  `int_column6` bigint(20) COMMENT '预留整数字段6',
  `int_column7` bigint(20) COMMENT '预留整数字段7',
  `int_column8` bigint(20) COMMENT '预留整数字段8',
  `int_column9` bigint(20) COMMENT '预留整数字段9',
  `int_column10` bigint(20) COMMENT '预留整数字段10',
  `int_column11` bigint(20) COMMENT '预留整数字段11',
  `int_column12` bigint(20) COMMENT '预留整数字段12',
  `int_column13` bigint(20) COMMENT '预留整数字段13',
  `int_column14` bigint(20) COMMENT '预留整数字段14',
  `int_column15` bigint(20) COMMENT '预留整数字段15',
  `int_column16` bigint(20) COMMENT '预留整数字段16',
  `int_column17` bigint(20) COMMENT '预留整数字段17',
  `int_column18` bigint(20) COMMENT '预留整数字段18',
  `int_column19` bigint(20) COMMENT '预留整数字段19',
  `num_column0` decimal(30,8) COMMENT '预留数值字段0',
  `num_column1` decimal(30,8) COMMENT '预留数值字段1',
  `num_column2` decimal(30,8) COMMENT '预留数值字段2',
  `num_column3` decimal(30,8) COMMENT '预留数值字段3',
  `num_column4` decimal(30,8) COMMENT '预留数值字段4',
  `num_column5` decimal(30,8) COMMENT '预留数值字段5',
  `num_column6` decimal(30,8) COMMENT '预留数值字段6',
  `num_column7` decimal(30,8) COMMENT '预留数值字段7',
  `num_column8` decimal(30,8) COMMENT '预留数值字段8',
  `num_column9` decimal(30,8) COMMENT '预留数值字段9',
  `num_column10` decimal(30,8) COMMENT '预留数值字段10',
  `num_column11` decimal(30,8) COMMENT '预留数值字段11',
  `num_column12` decimal(30,8) COMMENT '预留数值字段12',
  `num_column13` decimal(30,8) COMMENT '预留数值字段13',
  `num_column14` decimal(30,8) COMMENT '预留数值字段14',
  `num_column15` decimal(30,8) COMMENT '预留数值字段15',
  `num_column16` decimal(30,8) COMMENT '预留数值字段16',
  `num_column17` decimal(30,8) COMMENT '预留数值字段17',
  `num_column18` decimal(30,8) COMMENT '预留数值字段18',
  `num_column19` decimal(30,8) COMMENT '预留数值字段19',
  `date_column0` datetime COMMENT '预留日期字段0',
  `date_column1` datetime COMMENT '预留日期字段1',
  `date_column2` datetime COMMENT '预留日期字段2',
  `date_column3` datetime COMMENT '预留日期字段3',
  `date_column4` datetime COMMENT '预留日期字段4',
  `date_column5` datetime COMMENT '预留日期字段5',
  `date_column6` datetime COMMENT '预留日期字段6',
  `date_column7` datetime COMMENT '预留日期字段7',
  `date_column8` datetime COMMENT '预留日期字段8',
  `date_column9` datetime COMMENT '预留日期字段9',
  `public_flag` char(1) NOT NULL DEFAULT 'N' COMMENT '跨租户共享标识，Y则共享，N不共享',
  `active_flag` char(1) NOT NULL DEFAULT 'Y' COMMENT '有效标识，Y有效，N无效',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` bigint(20) NOT NULL COMMENT '创建人ID，对用用户ID',
  `last_update_date` timestamp NOT NULL  DEFAULT CURRENT_TIMESTAMP COMMENT '最后更新时间',
  `last_update_by` bigint(20) NOT NULL COMMENT '最后更新人ID，对用用户ID',
  PRIMARY KEY (`data_id`),
  UNIQUE KEY `data_id` (`data_id`),
  KEY `system_entities_tenant_id_fk0` (`tenant_id`),
  KEY `system_entities_md_entity_id_fk0` (`md_entity_id`),
  CONSTRAINT `system_entities_md_entity_id_fk0` FOREIGN KEY (`md_entity_id`) REFERENCES `md_entities` (`md_entity_id`),
  CONSTRAINT `system_entities_tenant_id_fk0` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统对象表';


INSERT INTO `demo`.`md_tables` (`md_tables_id`, `tenant_id`, `database_id`, `schema_code`, `md_tables_name`, `md_tables_desc`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('10038', '100', 'localhost:3306/test', 'test', 'system_entities', '通用系统对象表', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '1001', '2020-12-28 11:34:56', '1001', '2021-01-28 10:23:22');

INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102001', '100', 'text_column0', 'text', '200', '0', 'Y', 'text_column0', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102002', '100', 'text_column1', 'text', '200', '0', 'Y', 'text_column1', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102003', '100', 'text_column2', 'text', '200', '0', 'Y', 'text_column2', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102004', '100', 'text_column3', 'text', '200', '0', 'Y', 'text_column3', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102005', '100', 'text_column4', 'text', '200', '0', 'Y', 'text_column4', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102006', '100', 'text_column5', 'text', '200', '0', 'Y', 'text_column5', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102007', '100', 'text_column6', 'text', '200', '0', 'Y', 'text_column6', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102008', '100', 'text_column7', 'text', '200', '0', 'Y', 'text_column7', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102009', '100', 'text_column8', 'text', '200', '0', 'Y', 'text_column8', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102010', '100', 'text_column9', 'text', '200', '0', 'Y', 'text_column9', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102011', '100', 'num_column0', 'decimal', '30', '8', 'Y', 'num_column0', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-22 11:02:25', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102012', '100', 'num_column1', 'decimal', '30', '8', 'Y', 'num_column1', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-22 11:02:25', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102013', '100', 'num_column2', 'decimal', '30', '8', 'Y', 'num_column2', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-22 11:02:25', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102014', '100', 'num_column3', 'decimal', '30', '8', 'Y', 'num_column3', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-22 11:02:25', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102015', '100', 'num_column4', 'decimal', '30', '8', 'Y', 'num_column4', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-22 11:02:25', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102016', '100', 'num_column5', 'decimal', '30', '8', 'Y', 'num_column5', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-22 11:02:25', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102017', '100', 'date_column0', 'datetime', NULL, NULL, 'Y', 'date_column0', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-22 11:04:46', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102018', '100', 'date_column1', 'datetime', NULL, NULL, 'Y', 'date_column1', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-22 11:04:46', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102019', '100', 'date_column2', 'datetime', NULL, NULL, 'Y', 'date_column2', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-22 11:04:46', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102020', '100', 'date_column3', 'datetime', NULL, NULL, 'Y', 'date_column3', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-22 11:04:46', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('102021', '100', 'data_id', 'number', '20', '0', 'Y', '主键id', 'Y', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1', '2021-01-12 11:35:47', '1', '2020-12-28 11:43:00');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156541', '100', 'text_column10', 'varchar', '512', NULL, 'Y', '预留文本字段10', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156542', '100', 'text_column11', 'varchar', '512', NULL, 'Y', '预留文本字段11', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156543', '100', 'text_column12', 'varchar', '512', NULL, 'Y', '预留文本字段12', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156544', '100', 'text_column13', 'varchar', '512', NULL, 'Y', '预留文本字段13', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156545', '100', 'text_column14', 'varchar', '512', NULL, 'Y', '预留文本字段14', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156546', '100', 'text_column15', 'varchar', '512', NULL, 'Y', '预留文本字段15', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156547', '100', 'text_column16', 'varchar', '512', NULL, 'Y', '预留文本字段16', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156548', '100', 'text_column17', 'varchar', '512', NULL, 'Y', '预留文本字段17', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156549', '100', 'text_column18', 'varchar', '512', NULL, 'Y', '预留文本字段18', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156550', '100', 'text_column19', 'varchar', '512', NULL, 'Y', '预留文本字段19', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156551', '100', 'text_column20', 'varchar', '512', NULL, 'Y', '预留文本字段20', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156552', '100', 'text_column21', 'varchar', '512', NULL, 'Y', '预留文本字段21', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156553', '100', 'text_column22', 'varchar', '512', NULL, 'Y', '预留文本字段22', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156554', '100', 'text_column23', 'varchar', '512', NULL, 'Y', '预留文本字段23', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156555', '100', 'text_column24', 'varchar', '512', NULL, 'Y', '预留文本字段24', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156556', '100', 'text_column25', 'varchar', '512', NULL, 'Y', '预留文本字段25', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156557', '100', 'text_column26', 'varchar', '512', NULL, 'Y', '预留文本字段26', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156558', '100', 'text_column27', 'varchar', '512', NULL, 'Y', '预留文本字段27', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:06', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156559', '100', 'text_column28', 'varchar', '512', NULL, 'Y', '预留文本字段28', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156560', '100', 'text_column29', 'varchar', '512', NULL, 'Y', '预留文本字段29', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156561', '100', 'text_column30', 'varchar', '512', NULL, 'Y', '预留文本字段30', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156562', '100', 'text_column31', 'varchar', '512', NULL, 'Y', '预留文本字段31', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156563', '100', 'text_column32', 'varchar', '512', NULL, 'Y', '预留文本字段32', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156564', '100', 'text_column33', 'varchar', '512', NULL, 'Y', '预留文本字段33', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156565', '100', 'text_column34', 'varchar', '512', NULL, 'Y', '预留文本字段34', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156566', '100', 'text_column35', 'varchar', '512', NULL, 'Y', '预留文本字段35', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156567', '100', 'text_column36', 'varchar', '512', NULL, 'Y', '预留文本字段36', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156568', '100', 'text_column37', 'varchar', '512', NULL, 'Y', '预留文本字段37', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156569', '100', 'text_column38', 'varchar', '512', NULL, 'Y', '预留文本字段38', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156570', '100', 'text_column39', 'varchar', '512', NULL, 'Y', '预留文本字段39', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156571', '100', 'char_column0', 'char', '10', NULL, 'Y', '预留char字段0', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156572', '100', 'char_column1', 'char', '10', NULL, 'Y', '预留char字段1', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156573', '100', 'char_column2', 'char', '10', NULL, 'Y', '预留char字段2', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156574', '100', 'char_column3', 'char', '10', NULL, 'Y', '预留char字段3', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156575', '100', 'char_column4', 'char', '10', NULL, 'Y', '预留char字段4', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156576', '100', 'char_column5', 'char', '10', NULL, 'Y', '预留char字段5', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156577', '100', 'char_column6', 'char', '10', NULL, 'Y', '预留char字段6', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156578', '100', 'char_column7', 'char', '10', NULL, 'Y', '预留char字段7', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156579', '100', 'char_column8', 'char', '10', NULL, 'Y', '预留char字段8', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156580', '100', 'char_column9', 'char', '10', NULL, 'Y', '预留char字段9', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:13', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156581', '100', 'int_column1', 'bigint', '19', '0', 'Y', '预留整数字段1', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 11:03:45', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156582', '100', 'int_column2', 'bigint', '19', '0', 'Y', '预留整数字段2', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 11:03:45', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156583', '100', 'int_column3', 'bigint', '19', '0', 'Y', '预留整数字段3', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 11:03:45', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156584', '100', 'int_column4', 'bigint', '19', '0', 'Y', '预留整数字段4', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 11:03:45', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156585', '100', 'int_column5', 'bigint', '19', '0', 'Y', '预留整数字段5', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 11:03:45', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156586', '100', 'int_column6', 'bigint', '19', '0', 'Y', '预留整数字段6', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156587', '100', 'int_column7', 'bigint', '19', '0', 'Y', '预留整数字段7', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156588', '100', 'int_column8', 'bigint', '19', '0', 'Y', '预留整数字段8', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156589', '100', 'int_column9', 'bigint', '19', '0', 'Y', '预留整数字段9', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156590', '100', 'int_column10', 'bigint', '19', '0', 'Y', '预留整数字段10', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156591', '100', 'int_column11', 'bigint', '19', '0', 'Y', '预留整数字段11', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156592', '100', 'int_column12', 'bigint', '19', '0', 'Y', '预留整数字段12', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156593', '100', 'int_column13', 'bigint', '19', '0', 'Y', '预留整数字段13', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156594', '100', 'int_column14', 'bigint', '19', '0', 'Y', '预留整数字段14', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156595', '100', 'int_column15', 'bigint', '19', '0', 'Y', '预留整数字段15', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156596', '100', 'int_column16', 'bigint', '19', '0', 'Y', '预留整数字段16', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156597', '100', 'int_column17', 'bigint', '19', '0', 'Y', '预留整数字段17', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156598', '100', 'int_column18', 'bigint', '19', '0', 'Y', '预留整数字段18', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156599', '100', 'int_column19', 'bigint', '19', '0', 'Y', '预留整数字段19', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156606', '100', 'num_column6', 'decimal', '30', '8', 'Y', '预留数值字段6', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156607', '100', 'num_column7', 'decimal', '30', '8', 'Y', '预留数值字段7', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156608', '100', 'num_column8', 'decimal', '30', '8', 'Y', '预留数值字段8', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156609', '100', 'num_column9', 'decimal', '30', '8', 'Y', '预留数值字段9', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156610', '100', 'num_column10', 'decimal', '30', '8', 'Y', '预留数值字段10', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156611', '100', 'num_column11', 'decimal', '30', '8', 'Y', '预留数值字段11', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156612', '100', 'num_column12', 'decimal', '30', '8', 'Y', '预留数值字段12', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:18', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156613', '100', 'num_column13', 'decimal', '30', '8', 'Y', '预留数值字段13', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156614', '100', 'num_column14', 'decimal', '30', '8', 'Y', '预留数值字段14', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156615', '100', 'num_column15', 'decimal', '30', '8', 'Y', '预留数值字段15', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156616', '100', 'num_column16', 'decimal', '30', '8', 'Y', '预留数值字段16', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156617', '100', 'num_column17', 'decimal', '30', '8', 'Y', '预留数值字段17', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156618', '100', 'num_column18', 'decimal', '30', '8', 'Y', '预留数值字段18', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156619', '100', 'num_column19', 'decimal', '30', '8', 'Y', '预留数值字段19', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156624', '100', 'date_column4', 'datetime', NULL, NULL, 'Y', '预留日期字段4', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156625', '100', 'date_column5', 'datetime', NULL, NULL, 'Y', '预留日期字段5', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156626', '100', 'date_column6', 'datetime', NULL, NULL, 'Y', '预留日期字段6', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156627', '100', 'date_column7', 'datetime', NULL, NULL, 'Y', '预留日期字段7', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156628', '100', 'date_column8', 'datetime', NULL, NULL, 'Y', '预留日期字段8', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156629', '100', 'date_column9', 'datetime', NULL, NULL, 'Y', '预留日期字段9', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156630', '100', 'active_flag', 'char', '1', NULL, 'N', '有效标识，Y有效，N无效', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156631', '100', 'create_date', 'timestamp', NULL, NULL, 'N', '创建时间', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156632', '100', 'create_by', 'bigint', '19', '0', 'N', '创建人ID，对用用户ID', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156633', '100', 'last_update_date', 'timestamp', NULL, NULL, 'N', '最后更新时间', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
INSERT INTO `demo`.`md_columns` (`md_columns_id`, `tenant_id`, `md_columns_name`, `md_columns_type`, `md_columns_length`, `md_dec_length`, `is_cols_null`, `md_columns_desc`, `is_key`, `public_flag`, `text_column1`, `text_column2`, `text_column3`, `text_column4`, `text_column5`, `int_column1`, `int_column2`, `int_column3`, `num_column1`, `num_column2`, `num_column3`, `date_column1`, `date_column2`, `date_column3`, `active_flag`, `md_tables_id`, `create_by`, `create_date`, `last_update_by`, `last_update_date`) VALUES ('156634', '100', 'last_update_by', 'bigint', '19', '0', 'N', '最后更新人ID，对用用户ID', 'N', 'Y', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Y', '10038', '1003', '2021-01-22 10:52:26', '1003', '2021-01-22 10:50:40');
commit;
