
# ###constants.py

# 权限控制对象类型，实体，视图，或service
ENTITY_TYPE_ENTITY = "Entity"
ENTITY_TYPE_VIEW = "View"
ENTITY_TYPE_SERVICE = "Service"


# 权限类型
PRIVILEGE_TYPE_CREATE = "CREATE"
PRIVILEGE_TYPE_UPDATE = "UPDATE"
PRIVILEGE_TYPE_READ = "READ"
PRIVILEGE_TYPE_DELETE = "DELETE"

